FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
RUN npm install -g pnpm

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./packages ./packages
COPY ./apps/web  ./apps/web 

RUN pnpm install

RUN pnpm run db:generate

RUN DATABASE_URL=${DATABASE_URL} pnpm run build 

EXPOSE 3000

CMD [ "pnpm", "run", "start:web" ]