name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.backend
          push: true
          tags: shubhamsharma10/user-app-backend:${{ github.sha }}

      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.49.77.4 -t "sudo docker stop user_backend && sudo docker rm user_backend && sudo docker run --name user_backend -d -p 8080:8080 shubhamsharma10/user-app-backend:${{ github.sha }}"